# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               The Clockwork Mind
tagline:             'Life as an analog to digital converter'
description:         'Reading maketh a full man, conference a ready man, and writing an exact man. - Francis Bacon'
url:                 http://www.clockworkmind.com
baseurl:             ''
paginate:            5
highlighter:         pygments

# About/contact
author:
  name:              Shane Thacker
  url:               https://twitter.com/shanethacker
  email:             sst@clockworkmind.com

# Custom vars
version:             0.0.1
