# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               The Clockwork Mind
tagline:             '...armed with the knowledge you get by simply paying attention...'
description:         'Reading maketh a full man, conference a ready man, and writing an exact man. - Francis Bacon'
url:                 https://www.clockworkmind.com
enforce_ssl:         www.clockworkmind.com
baseurl:             ''
paginate:            5
markdown:            kramdown
highlighter:         rouge

# About/contact
author:
  name:              Shane Thacker
  url:               https://twitter.com/shanethacker
  email:             sst@clockworkmind.com

# Custom vars
version:             0.0.2
